#-------------------------
# prod
# application-prod.yml
#-------------------------
spring:
  #-------------------------
  # spring.datasource
  #-------------------------
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/hanexdb
    driverClassName: org.postgresql.Driver
    username: hanex
    password: hanex1234
  #-------------------------
  # REDIS (spring.redis)
  #-------------------------
  redis:
    cluster:
      mode: true
      # 6379 : master , 6380 slave
      nodes: redis-service.redis:6379,redis-service.redis:6380
      max-redirect: 3
  #--------------------------
  # spring.cloud.stream (kafka 설정)
  #--------------------------
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka-headless.kafka:9092, kafka-headless.kafka:9093

#-------------------------
# swagger (springdoc-openapi)
# production 에서는 swagger 비활성화
#-------------------------
springdoc:
  swagger-ui:
    enabled: false # swagger-ui 비활성화
  api-docs:
    enabled: false

#--------------------------
# API CONFIG
#--------------------------
api:
  auth-service:
    url: http://auth-service.auth.svc.cluster.local:18080