#-------------------------
# local
# application-local.yml
#-------------------------
spring:
  datasource:
    url: jdbc:postgresql://192.168.41.50:5432/openmsadb
    driverClassName: org.postgresql.Driver
    username: openmsauser
    password: open1234!!
    # url: jdbc:postgresql://localhost:5432/test
    # driverClassName: org.postgresql.Driver
    # username: ray
    # password: 123456
    # url: jdbc:h2:mem:starter;MODE=PostgreSQL;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=true
    #url: jdbc:h2:mem:starter;INIT=RUNSCRIPT FROM 'classpath:db/ddl.sql';MODE=PostgreSQL;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=true
    #url: jdbc:h2:~/starter;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    # driver-class-name: org.h2.Driver
    # username: sa
    # password:
  h2:
    console:
      enabled: true
      #path: /h2-console  # H2 Console의 Path

  #-------------------------
  # spring.redis
  #-------------------------
  redis:
    # host: host.docker.internal
    host: 192.168.41.50 #로컬접속용 개발서버 설치 redis
    # host: localhost
    port: 6379
    cluster:
      mode: false
  #--------------------------
  # spring.session
  #--------------------------
  session:
    store-type: redis
    redis:
      namespace: web-oss-portal
  #--------------------------
  # spring.cloud.stream (kafka 설정)
  #--------------------------
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.41.50:9092 #로컬접속용 개발서버 설치 kafka
          # brokers: localhost:29092
          # zkNodes: localhost:22181

logging:
  config: classpath:log4j2-local.xml

#--------------------------
# API CONFIG
#--------------------------
api:
  # connect to dev api-auth
  auth-service:
    # 접근 토큰과 갱신 토큰을 가져오기 위한 api-auth의 url입니다.
    url: http://dev-api-auth.openmsa.io

  # Nexus Repository Manager 3 연결관련 설정
  nexus:
    # base-url: http://192.168.41.50:8081
    base-url: http://127.0.0.1:8081
    username: admin
    password: password1201
    # password: osckorea!
    external: ${api.nexus.base-url}/service/extdirect
    internal: ${api.nexus.base-url}/service/rest/internal
    public: ${api.nexus.base-url}/service/rest/v1
