#-------------------------
# dev
# application-dev.yml
#-------------------------
spring:
  #-------------------------
  # spring.datasource
  #-------------------------
  datasource:
    url: jdbc:postgresql://192.168.41.50:5432/openmsadb
    driverClassName: org.postgresql.Driver
    username: openmsauser
    password: open1234!!

  #-------------------------
  # spring.redis
  #-------------------------
  redis:
    cluster:
      mode: true
      # 6379 : master , 6380 slave
      # nodes: redis-service.redis:6379,redis-service.redis:6380
      nodes:
        - redis-service.redis:6379
      max-redirect: 3
  #--------------------------
  # spring.cloud.stream (kafka 설정)
  #--------------------------
  cloud:
    stream:
      kafka:
        binder:
          # brokers: kafka-headless.kafka:9092, kafka-headless.kafka:9093
          brokers: 
            - kafka-headless.kafka:9092
          # brokers:
          # - kafka-0.kafka-headless.kafka.svc.cluster.local:9092
          # - kafka-1.kafka-headless.kafka.svc.cluster.local:9092
          # - kafka-2.kafka-headless.kafka.svc.cluster.local:9092



#-------------------------
# logging
#-------------------------
logging:
  config: classpath:log4j2-dev.xml

#--------------------------
# API CONFIG
#--------------------------
api:
  auth-service:
    # url: http://auth-service-svc.fms.svc:8080
    url: http://api-auth-svc.openmsa.svc:8080