#-----------------------
# component.http
# Component 검색 관련 API
#-----------------------

### 변수 값
// 저장소 이름
@repository=maven-central

#-----------------------

### 1. 특정 저장소의 Component 목록 조회
GET /v1/components/{{repository}}
Host: localhost:8080

### 2. 특정 저장소의 Component 목록 수 조회
GET /v1/components/count/{{repository}}
Host: localhost:8080